baseURL: "https://l4n22.github.io/"
title: L4n22 Blog
theme: ["PaperMod"]

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
  #pygmentsUseClasses: true
  #mainsections: ["posts", "pa"]
# googleAnalytics: UA-123-45

minify:
  disableXML: true
  # minifyOutput: true

languages:
  en:
    languageName: "English"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: Search
          url: search/
          weight: 5
        - name: Tags
          url: tags/
          weight: 10
        - name: Archive
          url: archives
          weight: 15


outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  author: ["L4n22"] # multiple authors

  defaultTheme: auto
  # disableThemeToggle: true
  #ShowShareButtons: true
  ShowReadingTime: true
  # disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
    #ShowRssButtonInSectionTermList: true
  ShowAllPagesInArchive: true
  ShowPageNums: true
  ShowToc: true
  # comments: false
  #  images: ["images/papermod-cover.png"]

    #  profileMode:
    #    enabled: false
    #    title: PaperMod
    #    imageUrl: "#"
    #    imageTitle: my image
    #    # imageWidth: 120
        # imageHeight: 120
        #    buttons:
        #      - name: Archives
        #        url: archives
        #      - name: Tags
        #        url: tags

  homeInfoParams:
    Title: "L4n22 Blog"
    Content: >
      👋 Welcome to my blog!

  socialIcons:
    - name: github
      title: View Source on Github
      url: "https://github.com/l4n22"
        #            - name: Discord
        #      title: Join discord community
        #      url: "https://discord.gg/ahpmTvhVmp"
    - name: telegram
      title: Join the Telegram community
      url: "#"


  assets:
    disableHLJS: true
  #     favicon: "<link / abs url>"
  #     favicon16x16: "<link / abs url>"
  #     favicon32x32: "<link / abs url>"
  #     apple_touch_icon: "<link / abs url>"
  #     safari_pinned_tab: "<link / abs url>"

  # cover:
  #     hidden: true # hide everywhere but not in structured data
  #     hiddenInList: true # hide on list pages and home
  #     hiddenInSingle: true # hide on single page

  # fuseOpts:
  #     isCaseSensitive: false
  #     shouldSort: true
  #     location: 0
  #     distance: 1000
  #     threshold: 0.4
  #     minMatchCharLength: 0
  #     keys: ["title", "permalink", "summary", "content"]

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

# privacy:
#   vimeo:
#     disabled: false
#     simple: true

#   twitter:
#     disabled: false
#     enableDNT: true
#     simple: true

#   instagram:
#     disabled: false
#     simple: true

#   youtube:
#     disabled: false
#     privacyEnhanced: true

      #services:
      #  instagram:
      #    disableInlineCSS: true
      #  twitter:
      #    disableInlineCSS: true
