# https://github.com/adityatelange/hugo-PaperMod/wiki/Features

baseURL: "https://l4n22.github.io/"
title: "Pwn3d Blog"
theme: ["PaperMod"]
enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
minify:
  disableXML: true
languages:
  en:
    languageName: "English"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: "Search"
          url: "search/"
          weight: 5
        - name: "Tags"
          url: "tags/"
          weight: 10
        - name: "Archive"
          url: "archives"
          weight: 15
params:
  author: ["L4n22"] # multiple authors
  defaultTheme: auto
  ShowReadingTime: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowAllPagesInArchive: true
  ShowPageNums: true
  ShowToc: true
  #images: ["images/download.jpg"]
  profileMode:
    enabled: true
    title: "I'm L4n22"
    subtitle: "Cybersecurity enthusiast ❤"
    imageUrl: "https://avatars.githubusercontent.com/u/89106058?v=4"
    imageWidth: 120
    imageHeight: 120
    buttons:
      - name: Posts
        url: "/posts"
 
  homeInfoParams:
    Title: "L4n22 Blog"
    Content: "👋 Welcome to my blog!"
    socialIcons:
      - name: github
        title: "View Source on Github"
        url: "https://github.com/l4n22"
      - name: telegram
        title: "Join the Telegram community"
        url: "#"
  assets:
    disableHLJS: true
outputs:
  home:
    - HTML
    - RSS
    - JSON
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false